name: tafqit
description: Tafqit a  Dart/Flutter  package  to convert a numbers to Arabic text words.
version: 0.0.3
# homepage: https://www.example.com
repository: https://github.com/kflihan/tafqit

environment:
  sdk: '>=2.17.0 <3.0.0'



dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
